### PR TITLE
Format to be pep8 compatible

### PR DESCRIPTION
**Pull request by myoung34**
Before:

```
$ flake8 eb-platform-update-notify-slack.py | awk '{print $2}' | sort | uniq
E101
E122
E131
E201
E202
E203
E225
E231
E265
E302
E401
E501
E999
W191
```

After:

```
$ flake8 eb-platform-update-notify-slack.py
$ echo $?
0
```

Also fixed typos on lines 38 and 77

### CODE REVIEW

**Comment by dnorth98** [comment]
Thanks for the PR!  Question though - why so many exclusions with the noqa directive?

**Comment by myoung34** [comment]
Autoformat (80 character lines is a stupid error) because im lazy. Its also good to be specific, but no reason other than that

**Comment by dnorth98** [comment]
I'm thinking that rather than have all the noqa directives, why don't we modify the travis build to call flake8 BUT exclude the E501s? Something like in this example:

https://fangpenlin.com/posts/2013/09/19/fall-in-love-with-continuous-testing-and-integration-travis-ci/

**Comment by myoung34** [comment]
@dnorth98 done

**Pull request merged**
